# Generated by Django 4.0.3 on 2022-05-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dios',
            fields=[
                ('id_dios', models.AutoField(primary_key=True, serialize=False)),
                ('nom_dios', models.CharField(max_length=100)),
                ('email_dios', models.EmailField(max_length=100)),
                ('logo_dios', models.ImageField(upload_to='ImageDios/')),
                ('description_dios', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nom_admin', models.CharField(max_length=50)),
                ('premon_admin', models.CharField(max_length=100)),
                ('photo_admin', models.ImageField(upload_to='ImageAdmin/')),
                ('email_admin', models.EmailField(max_length=500)),
                ('password_admin', models.CharField(max_length=500)),
                ('dios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDios.dios')),
            ],
        ),
        migrations.CreateModel(
            name='Bannir_vendor',
            fields=[
                ('id_bannir', models.AutoField(primary_key=True, serialize=False)),
                ('lib_bannir', models.CharField(max_length=100)),
                ('admin', models.CharField(max_length=500)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Bannir_customer',
            fields=[
                ('id_bannir', models.AutoField(primary_key=True, serialize=False)),
                ('lib_bannir', models.CharField(max_length=100)),
                ('admin', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id_annonce', models.AutoField(primary_key=True, serialize=False)),
                ('lib_annonce', models.TextField()),
                ('contenu_annonce', models.FileField(upload_to='annonce/')),
                ('date_annonce', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDios.user')),
            ],
        ),
    ]
