# Generated by Django 4.1.2 on 2022-10-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_admin',
            new_name='email_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_admin',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nom_admin',
            new_name='nom_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password_admin',
            new_name='password_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='photo_admin',
            new_name='photo_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='premon_admin',
            new_name='premon_user',
        ),
    ]
