# Generated by Django 4.0.3 on 2022-05-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('nom_customer', models.CharField(max_length=50)),
                ('premon_customer', models.CharField(max_length=100)),
                ('email_customer', models.EmailField(max_length=100)),
                ('number_customer', models.CharField(max_length=15)),
                ('lieuHabit_customer', models.CharField(max_length=100)),
                ('age_customer', models.CharField(max_length=150)),
                ('pwd_customer', models.CharField(max_length=500)),
                ('status_customer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EtatCivil',
            fields=[
                ('id_etatCivil', models.AutoField(primary_key=True, serialize=False)),
                ('lib_etatCivil', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadImage',
            fields=[
                ('id_downloadImage', models.AutoField(primary_key=True, serialize=False)),
                ('lib_downloadImage', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='EtatCivil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.etatcivil'),
        ),
    ]
